sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alex1311/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alex1311/react-test npm test

after_success:
  - docker build -t alex1311/multi-client ./client
  - docker build -t alex1311/multi-nginx ./nginx
  - docker build -t alex1311/multi-server ./server
  - docker build -t alex1311/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push alex1311/multi-client
  - docker push alex1311/multi-nginx
  - docker push alex1311/multi-server
  - docker push alex1311/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'Multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-210575857620'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

